"""
The **build** stage — deterministic emit of the spec-derived artifacts.

Reads the precise ``layer2.params.yaml`` + ``layer3.subparts/*.yaml`` and writes the
app's owned files:

  - ``domain/identity.py``   — operator-facing labels (brand tokens stay)
  - ``fleet/fleet.yaml``     — inventory seed (real hosts are LIVE, edited in-app)
  - ``commands/commands_{host,roleA,roleB}.yaml`` — the `live` command buttons
  - ``networks/networks.yaml``  — top-bar LEDs (when a `networks` sub-part is given)
  - ``domain/sequences.yaml``   — bring-up/tear-down order (when a `sequence` sub-part is given)
  - ``domain/gates.py``         — gate thresholds patched (when a `gate-*` sub-part overrides them)

"Skip a sub-part → template default" (R2): anything not described is left as the
forked template's file. Every emitted path is recorded in the manifest, and the build
writes a **compile report** (specified vs inferred + TODOs — never a silent guess, §6).

This stage is a *pure data transform* (the plan's goal of maximizing the
deterministic share); the LLM is reserved for distill/expand and for free-form gate
logic, which this stage flags as a TODO rather than guessing.
"""

import os
import re
from typing import Any, Dict, List, Tuple

import yaml

from .manifest import Manifest

GATE_KEYS = ("A", "B", "C", "D")


# --- small helpers -----------------------------------------------------------
def _app(params: Dict[str, Any]) -> Dict[str, Any]:
    return params.get("app") or params


def _slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_-]+", "-", str(name)).strip("-")
    return s or "fleet"


def _write(app_dir: str, relpath: str, text: str, manifest: Manifest):
    full = os.path.join(app_dir, relpath)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    manifest.record(relpath)


def _yaml_block(data: Any) -> str:
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False)


# --- identity ----------------------------------------------------------------
def emit_identity(app_dir: str, params: Dict[str, Any], subparts: Dict[str, Any],
                  manifest: Manifest, report: List[str]):
    a = _app(params)
    over = subparts.get("identity") or {}
    name = over.get("app_name") or a.get("name", "ccFleet")
    tagline = over.get("tagline") or a.get("tagline", "Command & Control")
    brand = a.get("brand") or {}
    lead = over.get("brand_lead") or brand.get("lead") or name[:2]
    accent = over.get("brand_accent") or brand.get("accent") or name[2:] or name
    node_rep = ((a.get("node") or {}).get("represents")
                or over.get("node_represents") or "a fleet node")
    roles = a.get("roles") or {"roleA": "roleA", "roleB": "roleB"}
    services = a.get("services") or {"serviceA": "serviceA", "serviceB": "serviceB",
                                     "serviceC": "serviceC"}
    variants = a.get("variants") or {"A": "variant A", "B": "variant B"}
    gates_map = a.get("gates") or {"A": "reach", "B": "proc", "C": "check", "D": "link"}
    gates = [{"key": k, "label": str(gates_map[k])} for k in GATE_KEYS if k in gates_map]

    identity = {
        "app_name": str(name), "brand_lead": str(lead), "brand_accent": str(accent),
        "tagline": str(tagline), "node_represents": str(node_rep),
        "roles": {k: str(v) for k, v in roles.items()},
        "services": {k: str(v) for k, v in services.items()},
        "variants": {k: str(v) for k, v in variants.items()},
        "gates": gates,
    }
    body = (
        '"""domain/identity.py — operator-facing labels (GENERATED by the Compiler).\n\n'
        'Brand *tokens* in code (ccflet / CCFlet / CCFLET_ / /tmp/ccflet / X-CCFlet-User)\n'
        'are load-bearing and never renamed; only these display labels come from the spec.\n'
        '"""\n\n'
        f"IDENTITY = {_pyrepr(identity)}\n\n\n"
        'def gate_label(key: str) -> str:\n'
        '    for g in IDENTITY["gates"]:\n'
        '        if g["key"] == key:\n'
        '            return g["label"]\n'
        '    return key\n'
    )
    _write(app_dir, "domain/identity.py", body, manifest)
    report.append(f"identity: app_name={name!r}, {len(gates)} gate label(s)")


def _pyrepr(obj: Any, indent: int = 0) -> str:
    """Pretty, stable Python literal for the IDENTITY dict (deterministic output)."""
    pad = "    " * (indent + 1)
    close = "    " * indent
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        items = ",\n".join(f"{pad}{_pyrepr(k)}: {_pyrepr(v, indent + 1)}"
                           for k, v in obj.items())
        return "{\n" + items + ",\n" + close + "}"
    if isinstance(obj, list):
        if not obj:
            return "[]"
        items = ",\n".join(f"{pad}{_pyrepr(v, indent + 1)}" for v in obj)
        return "[\n" + items + ",\n" + close + "]"
    return repr(obj)


# --- fleet inventory ---------------------------------------------------------
def emit_fleet(app_dir: str, params: Dict[str, Any], manifest: Manifest,
               report: List[str]):
    a = _app(params)
    fleet_name = a.get("fleet_name") or _slug(a.get("name", "fleet"))
    d = a.get("defaults") or {}
    vp = a.get("variant_params") or {
        "A": {"addr": "10.0.0.255", "launcher": "variantA.run", "flag": ""},
        "B": {"addr": "{SUBNET}.255", "launcher": "variantB.run", "flag": "--variant-flag"},
    }
    nodes = a.get("nodes_seed")
    if not nodes:
        count = int((a.get("node") or {}).get("count", 3))
        nodes = [{"name": f"node{i}", "id": i, "host": f"10.0.0.{100 + i}",
                  "subnet": f"10.1.{i}"} for i in range(1, count + 1)]

    fleet = {
        "fleet": {
            "name": fleet_name,
            "defaults": {
                "variant": d.get("variant", "A"),
                "algo": d.get("algo", "default"),
                "roleA_user": d.get("roleA_user", "user"),
                "roleB_user": d.get("roleB_user", "root"),
                "key_file": d.get("key_file", "~/.ssh/id_rsa"),
                "deploy_root": d.get("deploy_root", "/srv/ccfleet/roleA"),
                "ssh_opts": d.get("ssh_opts",
                                  "-o BatchMode=yes -o StrictHostKeyChecking=no "
                                  "-o ConnectTimeout=5"),
                "stagger": d.get("stagger", 0.5),
                "roleB_host_suffix": d.get("roleB_host_suffix", ".2"),
                "variants": vp,
            },
            "nodes": nodes,
        }
    }
    groups = a.get("groups")
    if groups:
        fleet["fleet"]["groups"] = groups
    header = ("# fleet/fleet.yaml — inventory (GENERATED by the Compiler from "
              "system/layer2.params.yaml).\n"
              "# Real hosts/subnets are LIVE data: edit them on the app's Config page; "
              "this seed is a starting point.\n")
    _write(app_dir, "fleet/fleet.yaml", header + _yaml_block(fleet), manifest)
    report.append(f"fleet: {fleet_name!r}, {len(nodes)} node(s)")


# --- command catalog (live buttons) -----------------------------------------
# layer3 action sub-part stem -> emitted catalog file
_ACTION_FILES = {
    "host-actions": "commands/commands_host.yaml",
    "roleA-actions": "commands/commands_roleA.yaml",
    "roleB-actions": "commands/commands_roleB.yaml",
}
_ACTION_KEYS = ("label", "group", "scope", "run", "script", "timeout", "danger")


def emit_commands(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                  report: List[str]):
    for stem, relpath in _ACTION_FILES.items():
        sp = subparts.get(stem)
        if sp is None:
            continue
        items = sp.get("add") or []
        cmds: Dict[str, Any] = {}
        for it in items:
            if it.get("mode", "live") != "live":
                report.append(f"TODO: {stem}/{it.get('id')} is mode:frozen — command "
                              "buttons are live config; emitting as live anyway")
            cid = it.get("id")
            if not cid:
                report.append(f"TODO: {stem} has an item with no id — skipped")
                continue
            entry = {k: it[k] for k in _ACTION_KEYS if k in it}
            cmds[cid] = entry
        doc = {"settings": {"default_timeout": sp.get("default_timeout", 60)},
               "commands": cmds}
        header = (f"# {os.path.basename(relpath)} — operator command buttons "
                  "(GENERATED; mode: live, editable on the Config page).\n")
        _write(app_dir, relpath, header + _yaml_block(doc), manifest)
        report.append(f"commands[{stem}]: {len(cmds)} button(s)")


# --- networks (top-bar LEDs) -------------------------------------------------
def emit_networks(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                  report: List[str]):
    sp = subparts.get("networks")
    if sp is None:
        return
    doc = {"networks": {
        "poll_interval": sp.get("poll_interval", 5),
        "ping_timeout": sp.get("ping_timeout", 1),
        "links": sp.get("links", []),
    }}
    header = ("# networks/networks.yaml — base-station connectivity LEDs (GENERATED; "
              "LIVE — editable on the Config page).\n")
    _write(app_dir, "networks/networks.yaml", header + _yaml_block(doc), manifest)
    report.append(f"networks: {len(doc['networks']['links'])} link(s)")


# --- sequences (frozen: bring-up/tear-down order) ----------------------------
def emit_sequences(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                   report: List[str]):
    # a single `sequences` sub-part may carry the whole deploy/bring_up/tear_down map.
    sp = subparts.get("sequences")
    if sp is None:
        return
    body = {k: sp[k] for k in ("deploy", "bring_up", "tear_down", "invariants")
            if k in sp}
    header = ("# domain/sequences.yaml — variant-aware ordered sequences (GENERATED; "
              "frozen — change the spec + rebuild).\n")
    _write(app_dir, "domain/sequences.yaml", header + _yaml_block(body), manifest)
    report.append("sequences: regenerated from spec")


# --- gate threshold overrides (frozen) ---------------------------------------
_THRESHOLDS = ("LINK_FRESH_MS", "CHECK_FRESH_S", "CHECK_GOOD", "SERVICEC_MIN_UP")


def patch_gate_thresholds(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                          report: List[str]):
    """If any ``gate-*`` sub-part declares ``thresholds:``, patch the numbers in
    ``domain/gates.py`` deterministically (a regex on the constant lines). Free-form
    gate *logic* (``parse:``/``good:`` prose) is flagged as a TODO, never guessed."""
    overrides: Dict[str, Any] = {}
    for stem, sp in subparts.items():
        if not stem.startswith("gate"):
            continue
        for k, v in (sp.get("thresholds") or {}).items():
            if k in _THRESHOLDS:
                overrides[k] = v
        if sp.get("parse") or sp.get("good"):
            report.append(f"TODO: {stem} declares custom parse/good logic — review "
                          "domain/gates.py (LLM codegen needed for non-threshold changes)")
    if not overrides:
        return
    path = os.path.join(app_dir, "domain", "gates.py")
    with open(path, "r", encoding="utf-8") as fh:
        src = fh.read()
    for k, v in overrides.items():
        src = re.sub(rf"(?m)^{k}\s*=\s*[^\n#]+", f"{k} = {v!r}", src)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(src)
    manifest.record("domain/gates.py")
    report.append(f"gates: patched thresholds {', '.join(sorted(overrides))}")


# --- top-level ---------------------------------------------------------------
def build(app_dir: str, params: Dict[str, Any], subparts: Dict[str, Any]
          ) -> Tuple[Manifest, List[str]]:
    """Emit all spec-derived artifacts into ``app_dir``; return (manifest, report)."""
    manifest = Manifest(app_dir=app_dir)
    report: List[str] = ["# Compile report", ""]
    emit_identity(app_dir, params, subparts, manifest, report)
    emit_fleet(app_dir, params, manifest, report)
    emit_commands(app_dir, subparts, manifest, report)
    emit_networks(app_dir, subparts, manifest, report)
    emit_sequences(app_dir, subparts, manifest, report)
    patch_gate_thresholds(app_dir, subparts, manifest, report)
    return manifest, report
