"""
The **build** stage — deterministic emit of the spec-derived artifacts.

Reads the precise ``layer2.params.yaml`` + ``layer3.subparts/*.yaml`` and writes the
app's owned files:

  - ``domain/identity.py``   — operator-facing labels (brand tokens stay)
  - ``fleet/fleet.yaml``     — inventory seed (real hosts are LIVE, edited in-app)
  - ``commands/commands_{host,roleA,roleB}.yaml`` — the `live` command buttons
  - ``profiles/{roleA,roleB}.yaml`` — per-role action/collector/log catalogs (when a
    ``*-profile`` sub-part is given)
  - ``networks/networks.yaml``  — top-bar LEDs (when a `networks` sub-part is given)
  - ``domain/sequences.yaml``   — bring-up/tear-down order (when a `sequence` sub-part is given)
  - ``domain/gates.py``         — gate thresholds + string-contract vocabulary patched
    (when a `gate-*` sub-part overrides them)

"Skip a sub-part → template default" (R2): anything not described is left as the
forked template's file. Every emitted path is recorded in the manifest, and the build
writes a **compile report** (specified vs inferred + TODOs — never a silent guess, §6).

This stage is a *pure data transform* (the plan's goal of maximizing the
deterministic share); the LLM is reserved for distill/expand and for free-form gate
logic, which this stage flags as a TODO rather than guessing.
"""

import os
import re
from typing import Any, Dict, List, Tuple

import yaml

from .manifest import Manifest

GATE_KEYS = ("A", "B", "C", "D")


# --- small helpers -----------------------------------------------------------
def _app(params: Dict[str, Any]) -> Dict[str, Any]:
    return params.get("app") or params


def _slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_-]+", "-", str(name)).strip("-")
    return s or "fleet"


def _write(app_dir: str, relpath: str, text: str, manifest: Manifest):
    full = os.path.join(app_dir, relpath)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    manifest.record(relpath)


def _yaml_block(data: Any) -> str:
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False)


# --- identity ----------------------------------------------------------------
def _resolve_identity(params: Dict[str, Any], subparts: Dict[str, Any]) -> Dict[str, Any]:
    """Resolve the operator-facing labels from params + the optional ``identity``
    sub-part. Shared by ``emit_identity`` (writes ``domain/identity.py``) and
    ``emit_docs`` (relabels the Help tree) so both speak with one voice."""
    a = _app(params)
    over = subparts.get("identity") or {}
    name = over.get("app_name") or a.get("name", "ccFleet")
    tagline = over.get("tagline") or a.get("tagline", "Command & Control")
    brand = a.get("brand") or {}
    lead = over.get("brand_lead") or brand.get("lead") or name[:2]
    accent = over.get("brand_accent") or brand.get("accent") or name[2:] or name
    node_rep = ((a.get("node") or {}).get("represents")
                or over.get("node_represents") or "a fleet node")
    roles = a.get("roles") or {"roleA": "roleA", "roleB": "roleB"}
    services = a.get("services") or {"serviceA": "serviceA", "serviceB": "serviceB",
                                     "serviceC": "serviceC"}
    variants = a.get("variants") or {"A": "variant A", "B": "variant B"}
    gates_map = a.get("gates") or {"A": "reach", "B": "proc", "C": "check", "D": "link"}
    gates = [{"key": k, "label": str(gates_map[k])} for k in GATE_KEYS if k in gates_map]
    return {
        "app_name": str(name), "brand_lead": str(lead), "brand_accent": str(accent),
        "tagline": str(tagline), "node_represents": str(node_rep),
        "roles": {k: str(v) for k, v in roles.items()},
        "services": {k: str(v) for k, v in services.items()},
        "variants": {k: str(v) for k, v in variants.items()},
        "gates": gates,
    }


def emit_identity(app_dir: str, params: Dict[str, Any], subparts: Dict[str, Any],
                  manifest: Manifest, report: List[str]):
    identity = _resolve_identity(params, subparts)
    name = identity["app_name"]
    gates = identity["gates"]
    body = (
        '"""domain/identity.py — operator-facing labels (GENERATED by the Compiler).\n\n'
        'Brand *tokens* in code (ccflet / CCFlet / CCFLET_ / /tmp/ccflet / X-CCFlet-User)\n'
        'are load-bearing and never renamed; only these display labels come from the spec.\n'
        '"""\n\n'
        f"IDENTITY = {_pyrepr(identity)}\n\n\n"
        'def gate_label(key: str) -> str:\n'
        '    for g in IDENTITY["gates"]:\n'
        '        if g["key"] == key:\n'
        '            return g["label"]\n'
        '    return key\n'
    )
    _write(app_dir, "domain/identity.py", body, manifest)
    report.append(f"identity: app_name={name!r}, {len(gates)} gate label(s)")


def _pyrepr(obj: Any, indent: int = 0) -> str:
    """Pretty, stable Python literal for the IDENTITY dict (deterministic output)."""
    pad = "    " * (indent + 1)
    close = "    " * indent
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        items = ",\n".join(f"{pad}{_pyrepr(k)}: {_pyrepr(v, indent + 1)}"
                           for k, v in obj.items())
        return "{\n" + items + ",\n" + close + "}"
    if isinstance(obj, list):
        if not obj:
            return "[]"
        items = ",\n".join(f"{pad}{_pyrepr(v, indent + 1)}" for v in obj)
        return "[\n" + items + ",\n" + close + "]"
    return repr(obj)


# --- fleet inventory ---------------------------------------------------------
def emit_fleet(app_dir: str, params: Dict[str, Any], manifest: Manifest,
               report: List[str]):
    a = _app(params)
    fleet_name = a.get("fleet_name") or _slug(a.get("name", "fleet"))
    d = a.get("defaults") or {}
    vp = a.get("variant_params") or {
        "A": {"addr": "10.0.0.255", "launcher": "variantA.run", "flag": ""},
        "B": {"addr": "{SUBNET}.255", "launcher": "variantB.run", "flag": "--variant-flag"},
    }
    nodes = a.get("nodes_seed")
    if not nodes:
        count = int((a.get("node") or {}).get("count", 3))
        nodes = [{"name": f"node{i}", "id": i, "host": f"10.0.0.{100 + i}",
                  "subnet": f"10.1.{i}"} for i in range(1, count + 1)]

    fleet = {
        "fleet": {
            "name": fleet_name,
            "defaults": {
                "variant": d.get("variant", "A"),
                "algo": d.get("algo", "default"),
                "roleA_user": d.get("roleA_user", "user"),
                "roleB_user": d.get("roleB_user", "root"),
                "key_file": d.get("key_file", "~/.ssh/id_rsa"),
                "deploy_root": d.get("deploy_root", "/srv/ccfleet/roleA"),
                "ssh_opts": d.get("ssh_opts",
                                  "-o BatchMode=yes -o StrictHostKeyChecking=no "
                                  "-o ConnectTimeout=5"),
                "stagger": d.get("stagger", 0.5),
                "roleB_host_suffix": d.get("roleB_host_suffix", ".2"),
                "variants": vp,
            },
            "nodes": nodes,
        }
    }
    groups = a.get("groups")
    if groups:
        fleet["fleet"]["groups"] = groups
    header = ("# fleet/fleet.yaml — inventory (GENERATED by the Compiler from "
              "system/layer2.params.yaml).\n"
              "# Real hosts/subnets are LIVE data: edit them on the app's Config page; "
              "this seed is a starting point.\n")
    _write(app_dir, "fleet/fleet.yaml", header + _yaml_block(fleet), manifest)
    report.append(f"fleet: {fleet_name!r}, {len(nodes)} node(s)")


# --- command catalog (live buttons) -----------------------------------------
# layer3 action sub-part stem -> emitted catalog file
_ACTION_FILES = {
    "host-actions": "commands/commands_host.yaml",
    "roleA-actions": "commands/commands_roleA.yaml",
    "roleB-actions": "commands/commands_roleB.yaml",
}
_ACTION_KEYS = ("label", "group", "scope", "run", "script", "timeout", "danger")


def emit_commands(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                  report: List[str]):
    for stem, relpath in _ACTION_FILES.items():
        sp = subparts.get(stem)
        if sp is None:
            continue
        items = sp.get("add") or []
        cmds: Dict[str, Any] = {}
        for it in items:
            if it.get("mode", "live") != "live":
                report.append(f"TODO: {stem}/{it.get('id')} is mode:frozen — command "
                              "buttons are live config; emitting as live anyway")
            cid = it.get("id")
            if not cid:
                report.append(f"TODO: {stem} has an item with no id — skipped")
                continue
            entry = {k: it[k] for k in _ACTION_KEYS if k in it}
            cmds[cid] = entry
        doc = {"settings": {"default_timeout": sp.get("default_timeout", 60)},
               "commands": cmds}
        header = (f"# {os.path.basename(relpath)} — operator command buttons "
                  "(GENERATED; mode: live, editable on the Config page).\n")
        _write(app_dir, relpath, header + _yaml_block(doc), manifest)
        report.append(f"commands[{stem}]: {len(cmds)} button(s)")


# --- per-role profiles (action / collector / log catalogs) ------------------
# layer3 profile sub-part stem -> (role, emitted profile file)
_PROFILE_FILES = {
    "roleA-profile": ("roleA", "profiles/roleA.yaml"),
    "roleB-profile": ("roleB", "profiles/roleB.yaml"),
}


def emit_profiles(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                  report: List[str]):
    """Write ``profiles/{roleA,roleB}.yaml`` from the matching ``*-profile`` sub-parts.

    Skip a sub-part → the forked template's profile is kept (R2). The body is validated
    through the engine's own :func:`core.profiles.profile_from_dict` before it is
    persisted — an invalid profile aborts the build loudly (validate-first; never ship a
    broken file) rather than silently leaving the template default in place.
    """
    from core.profiles import profile_from_dict
    for stem, (role, relpath) in _PROFILE_FILES.items():
        sp = subparts.get(stem)
        if sp is None:
            continue
        body = {k: v for k, v in sp.items() if k != "extends"}
        body.setdefault("name", role)
        try:
            profile_from_dict(body, name=role)
        except ValueError as e:
            raise ValueError(f"{stem}: invalid profile — {e}") from e
        header = (f"# profiles/{role}.yaml — {role} action/collector/log catalog "
                  "(GENERATED; mode: live, editable on the Config page).\n")
        _write(app_dir, relpath, header + _yaml_block(body), manifest)
        report.append(f"profiles[{role}]: {len(body.get('actions') or {})} action(s), "
                      f"{len(body.get('collectors') or {})} collector(s)")


# --- networks (top-bar LEDs) -------------------------------------------------
def emit_networks(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                  report: List[str]):
    sp = subparts.get("networks")
    if sp is None:
        return
    doc = {"networks": {
        "poll_interval": sp.get("poll_interval", 5),
        "ping_timeout": sp.get("ping_timeout", 1),
        "links": sp.get("links", []),
    }}
    header = ("# networks/networks.yaml — base-station connectivity LEDs (GENERATED; "
              "LIVE — editable on the Config page).\n")
    _write(app_dir, "networks/networks.yaml", header + _yaml_block(doc), manifest)
    report.append(f"networks: {len(doc['networks']['links'])} link(s)")


# --- sequences (frozen: bring-up/tear-down order) ----------------------------
def emit_sequences(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                   report: List[str]):
    # a single `sequences` sub-part may carry the whole deploy/bring_up/tear_down map.
    sp = subparts.get("sequences")
    if sp is None:
        return
    body = {k: sp[k] for k in ("deploy", "bring_up", "tear_down", "invariants")
            if k in sp}
    header = ("# domain/sequences.yaml — variant-aware ordered sequences (GENERATED; "
              "frozen — change the spec + rebuild).\n")
    _write(app_dir, "domain/sequences.yaml", header + _yaml_block(body), manifest)
    report.append("sequences: regenerated from spec")


# --- gate thresholds + string-contract overrides (frozen) --------------------
# Numeric thresholds (patched as repr ints/floats) and the string-contract vocabulary
# (patched as repr strings). Both are named module-level constants in domain/gates.py;
# domain/mock_rules.py *imports* the contract strings, so patching gates.py re-emits BOTH
# halves of the mock↔status contract at once (CLAUDE.md §7) — they can't drift.
_THRESHOLDS = ("LINK_FRESH_MS", "CHECK_FRESH_S", "CHECK_GOOD", "SERVICEC_MIN_UP")
_CONTRACT = ("CHECK_TAG", "CHECK2_TAG", "PROBE_A_READY", "PROBE_B_OK",
             "CHECK_VALUE_KEY", "SIGNAL_KEY",
             "LINKS_CMD_MARK", "CHECK_LOG_MARK", "SERVICEC_LOG_MARK",
             "PROBE_A_CMD_MARK", "PROBE_B_CMD_MARK", "BUILD_CMD_MARK")


def _patch_const(src: str, name: str, literal: str) -> str:
    """Replace the value of a module-level ``name = <value>`` line, preserving any inline
    comment (so the generated module stays clean + valid). First match only."""
    pat = rf"(?m)^({re.escape(name)}\s*=\s*)[^\n#]*(#.*)?$"

    def repl(m: "re.Match") -> str:
        comment = m.group(2) or ""
        sep = "  " if comment else ""
        return f"{m.group(1)}{literal}{sep}{comment}"

    return re.sub(pat, repl, src, count=1)


def patch_gate_thresholds(app_dir: str, subparts: Dict[str, Any], manifest: Manifest,
                          report: List[str]):
    """Patch the numeric ``thresholds:`` and the string ``contract:`` vocabulary declared
    by any ``gate-*`` sub-part into ``domain/gates.py`` (a regex on the constant lines).

    The ``contract:`` strings (log tags + probe markers) are the *shared* half of the
    ``mock ↔ status`` string contract: ``domain/mock_rules.py`` imports them from
    ``domain/gates.py``, so patching the constant here re-emits the producer side too and
    the two halves stay in lock-step. Free-form ``parse:``/``good:`` logic is still
    flagged as a TODO, never guessed (systemPlan §6)."""
    nums: Dict[str, Any] = {}
    strs: Dict[str, str] = {}
    for stem, sp in subparts.items():
        if not stem.startswith("gate"):
            continue
        for k, v in (sp.get("thresholds") or {}).items():
            if k in _THRESHOLDS:
                nums[k] = v
        for k, v in (sp.get("contract") or {}).items():
            if k in _CONTRACT:
                strs[k] = str(v)
        if sp.get("parse") or sp.get("good"):
            report.append(f"TODO: {stem} declares custom parse/good logic — review "
                          "domain/gates.py (LLM codegen needed for non-threshold changes)")
    if not nums and not strs:
        return
    path = os.path.join(app_dir, "domain", "gates.py")
    with open(path, "r", encoding="utf-8") as fh:
        src = fh.read()
    for k, v in nums.items():
        src = _patch_const(src, k, repr(v))
    for k, v in strs.items():
        src = _patch_const(src, k, repr(v))
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(src)
    manifest.record("domain/gates.py")
    parts = []
    if nums:
        parts.append(f"thresholds {', '.join(sorted(nums))}")
    if strs:
        parts.append(f"contract {', '.join(sorted(strs))}")
    report.append(f"gates: patched {'; '.join(parts)}")


# --- Help docs (the design/ tree served on the Help page) --------------------
# The Help tree is the *engine* reference (shared across forks), so the build does NOT
# rename structural identifiers in it (``roleA`` / ``serviceA`` / ``GATE A`` are literal
# code/config references in those docs — renaming them would corrupt the reference). What
# the build *does* do, deterministically and per app:
#   1. generate ``design/00-about.md`` — this app's own front page + a glossary mapping
#      each engine key onto the spec's labels, so the shared docs read in the app's terms;
#   2. relabel only the unambiguous *display* tokens (the app name) across the tree, from
#      the pristine template source — brand tokens (ccflet/CCFlet/…) always stay.
_ABOUT_FILE = "00-about.md"
_TEMPLATE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _template_design_dir() -> str:
    """The pristine design/ source. The Compiler always runs from the template (the fork
    has no venv), so this is the canonical, un-mutated copy to transform from."""
    return os.path.join(_TEMPLATE_DIR, "design")


def _template_app_name(source_design: str) -> str:
    """The display name the source docs are written in (the from-token for relabeling).
    Read from the template's own identity so a future template rename still works."""
    try:
        ident_path = os.path.join(os.path.dirname(os.path.abspath(source_design)),
                                  "domain", "identity.py")
        ns: Dict[str, Any] = {}
        with open(ident_path, "r", encoding="utf-8") as fh:
            exec(compile(fh.read(), ident_path, "exec"), ns)  # template's own, trusted
        return (ns.get("IDENTITY") or {}).get("app_name") or "ccFleet"
    except Exception:
        return "ccFleet"


def _walk_md(root: str) -> List[str]:
    """Relpaths of every ``.md`` under ``root`` (dotfiles/dirs skipped), sorted."""
    out: List[str] = []
    root_real = os.path.realpath(root)
    for dirpath, dirnames, filenames in os.walk(root_real):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for fn in filenames:
            if fn.startswith(".") or not fn.lower().endswith(".md"):
                continue
            out.append(os.path.relpath(os.path.join(dirpath, fn), root_real))
    return sorted(out)


def _md_table(header: Tuple[str, str], rows: List[Tuple[str, str]]) -> str:
    lines = [f"| {header[0]} | {header[1]} |", "|---|---|"]
    lines += [f"| {a} | {b} |" for a, b in rows]
    return "\n".join(lines)


def _about_markdown(identity: Dict[str, Any]) -> str:
    """The generated ``design/00-about.md`` — app intro + the engine-key glossary."""
    app = identity["app_name"]
    tagline = identity["tagline"] or "Command & Control"
    roles = identity["roles"]
    services = identity["services"]
    variants = identity["variants"]

    def _present(v):
        return v if (v and v not in ("None", "null")) else None

    role_rows = [("`roleA`", _present(roles.get("roleA")) or "roleA")]
    rb = _present(roles.get("roleB"))
    role_rows.append(("`roleB`", rb or "— _(single-host nodes)_"))
    svc_rows = [(f"`{k}`", services[k]) for k in ("serviceA", "serviceB", "serviceC")
                if k in services]
    var_rows = [(f"`{k}`", variants[k]) for k in ("A", "B") if k in variants]
    gate_rows = [(f"`{g['key']}`", g["label"]) for g in identity["gates"]]

    fm = (f'---\ntitle: "About {app}"\norder: 0\n'
          f'summary: "What {app} is, and how its fleet vocabulary maps onto the '
          f'ccFleet engine."\n---\n\n')
    parts = [
        fm,
        f"# {app} — {tagline}\n",
        f"**{app}** is a fleet command-&-control application built on the **ccFleet** "
        "engine: bring a fleet of remote nodes **up** for a run, **watch** their health, "
        "and bring them **down** again — entirely over SSH, with **every action and "
        "result recorded**.\n",
        f"In **{app}**, a node represents **{identity['node_represents']}**.\n",
        f"> _This page is generated from the build spec (`system/`)._ The rest of this "
        "Help tree is the shared **ccFleet engine reference**: it documents the machinery "
        "using its structural keys (`roleA`, `serviceA`, GATE A …). Read those docs "
        f"through the glossary below — it maps each engine key onto {app}'s own "
        "vocabulary.\n",
        f"## {app} vocabulary\n",
        "### Roles\n" + _md_table(("Engine key", app), role_rows) + "\n",
        "### Services\n" + _md_table(("Engine key", app), svc_rows) + "\n",
        "### Variants\n" + _md_table(("Engine key", app), var_rows) + "\n",
        "### Health gates\n" + _md_table(("Gate", app), gate_rows) + "\n",
        "## Where to go next\n",
        "The shared engine reference (read it in "
        f"{app}'s terms using the glossary above):\n\n"
        "- **[Architecture](01-architecture.md)** — system shape & data flow\n"
        "- **[Scope & Principles](02-scope-and-decisions.md)** — the rules of the game\n"
        "- **[Fleet Model & Variants](03-fleet-and-variants.md)** — nodes, inventory, "
        "variants\n"
        "- **[Health & Gates](07-health-and-gates.md)** — collectors, parsers, the gates\n"
        "- **[Config & Commands](13-config-and-commands.md)** — what you tune from the "
        "browser\n"
        "- the full index in **[Overview & Index](00-README.md)**\n",
    ]
    return "\n".join(parts) + "\n"


def emit_docs(app_dir: str, params: Dict[str, Any], subparts: Dict[str, Any],
              manifest: Manifest, report: List[str], source_design: str = None):
    """Regenerate the Help (``design/``) tree for this app: a generated front page +
    glossary, plus app-name relabeling of the shared engine reference. Controlled by the
    optional ``docs`` sub-part (``generate_about`` / ``relabel_app_name`` /
    ``substitutions`` / ``exclude``)."""
    identity = _resolve_identity(params, subparts)
    sp = subparts.get("docs") or {}
    source = source_design or _template_design_dir()

    # substitution map — *display* tokens only; structural keys + brand tokens stay.
    subs: List[Tuple[str, str]] = []
    relabel = sp.get("relabel_app_name", True)
    if relabel:
        from_name = _template_app_name(source)
        to_name = identity["app_name"]
        if from_name and to_name and from_name != to_name:
            subs.append((from_name, to_name))
    for k, v in (sp.get("substitutions") or {}).items():
        subs.append((str(k), str(v)))
    exclude = set(sp.get("exclude") or [])

    copied = 0
    if os.path.isdir(source):
        for rel in _walk_md(source):
            if rel == _ABOUT_FILE or rel in exclude:
                continue
            with open(os.path.join(source, rel), "r", encoding="utf-8") as fh:
                text = fh.read()
            for a, b in subs:
                text = text.replace(a, b)
            _write(app_dir, os.path.join("design", rel), text, manifest)
            copied += 1
    else:
        report.append(f"TODO: docs source {source!r} not found — Help tree not regenerated")

    if sp.get("generate_about", True):
        _write(app_dir, os.path.join("design", _ABOUT_FILE),
               _about_markdown(identity), manifest)
        report.append(f"docs: generated front page → design/{_ABOUT_FILE} "
                      f"(+ {len(identity['gates'])} gate label(s) in the glossary)")
    relabel_note = f", relabeled {subs[0][0]!r}→{subs[0][1]!r}" if (relabel and subs) else ""
    report.append(f"docs: {copied} engine reference doc(s) regenerated{relabel_note}")


# --- top-level ---------------------------------------------------------------
def build(app_dir: str, params: Dict[str, Any], subparts: Dict[str, Any]
          ) -> Tuple[Manifest, List[str]]:
    """Emit all spec-derived artifacts into ``app_dir``; return (manifest, report)."""
    manifest = Manifest(app_dir=app_dir)
    report: List[str] = ["# Compile report", ""]
    emit_identity(app_dir, params, subparts, manifest, report)
    emit_fleet(app_dir, params, manifest, report)
    emit_commands(app_dir, subparts, manifest, report)
    emit_profiles(app_dir, subparts, manifest, report)
    emit_networks(app_dir, subparts, manifest, report)
    emit_sequences(app_dir, subparts, manifest, report)
    patch_gate_thresholds(app_dir, subparts, manifest, report)
    emit_docs(app_dir, params, subparts, manifest, report)
    return manifest, report
