"""
domain/ — the per-app **domain pack**: the spec-derived logic the generic engine
loads at runtime. In this template these files hold the default *ccFleet demo*
behaviour; in a forked app they are regenerated by the Compiler from ``system/``.

Owned surfaces (kept here so the Compiler can re-emit them as whole files):

  - :mod:`domain.mock_rules` — the ``--mock`` producer (supervisor/sequence command
    routing, the demo live-log content, and the ``gate_mock`` simulate hook)
  - :mod:`domain.gates`      — the ``--mock`` log/command **vocabulary** the live-log
    producers use (the *gate logic* itself is now operator-editable config under
    ``gates/``, parsed by the generic engine ``core/gates_config.py`` — see ``plan2.md``)
  - ``domain/sequences.yaml``  — variant-aware deploy/bring-up/tear-down step lists
  - :mod:`domain.identity`   — operator-facing names/labels (brand tokens stay)

The generic engine (``core/``, ``web/``) stays ≈ the template and is *not*
spec-derived, which keeps a fork close enough to pull upstream improvements.

Brand tokens are load-bearing — keep ``ccflet`` / ``CCFlet`` / ``CCFLET_`` /
``/tmp/ccflet`` / ``X-CCFlet-User`` exactly as they are (see CLAUDE.md §8).
"""

import os
from typing import Any, Dict

import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
SEQUENCES_PATH = os.path.join(_HERE, "sequences.yaml")

_sequences_cache: Dict[str, Any] = {}


def load_sequences(path: str = SEQUENCES_PATH) -> Dict[str, Any]:
    """Load (and cache) the variant-aware sequence definitions.

    The engine reads these to drive ``deploy`` / ``bring_up`` / ``tear_down`` in the
    operator-specified order; ordering invariants are enforced generically against
    the declared ``invariants:`` block (see :func:`core.sequences.validate`).
    """
    cached = _sequences_cache.get(path)
    if cached is None:
        with open(path, "r", encoding="utf-8") as fh:
            cached = yaml.safe_load(fh) or {}
        _sequences_cache[path] = cached
    return cached
